### ISSUE TITLE
Review and TODO - Victor

### ISSUE THREAD

**Issue by victorohden** [Dalla01/Segmentation_SamGeo_RiceFields#1]
**Important** - :<span style="color:red">*Delete this part after review* text</span>.
TODO - ideas
- [] We need to choose a license for the repo.
- [] Did you use a conda or pip environment? A requirements.txt or other could be good to set the Python version and package versions
- [] Describe the functions that will help the users to understand it. Just an idea, maybe is too much work for that.
- [] In [TimeSeriesExtraction.js](TimeSeriesExtraction.js), collection "collectionOriginalS2" you are using "COPERNICUS/S2_HARMONIZED" and not "COPERNICUS/S2_SR_HARMONIZED". Double-chek it.
- [x] I changed some Portuguese phrases and added some headers in your code, to highlight that you are the author.
- [ ] I committed all my changes in a new branch, please merge it if you agree with that.
